export const Images = {
  andy: '../assets/images/andy.jpg',
  businessIcon: '../assets/images/business.png',
  card: '../assets/images/card.png',
  cash: '../assets/images/cash.png',
  chip: '../assets/images/chip.png',
  coins: '../assets/images/coins.png',
  daniel: '../assets/images/daniel.jpg',
  desk: '../assets/images/desk.png',
  diagram: '../assets/images/8x-diagram.png',
  greenCheckmark: '../assets/images/green-checkmark.png',
  kamal: '../assets/images/kamal.jpg',
  kerman: '../assets/images/kerman.jpg',
  kevinL: '../assets/images/kevinl.jpg',
  kevinZ: '../assets/images/kevinz.jpg',
  memphisBackground: '../assets/images/memphis-colorful.png',
  overview: '../assets/images/overview.png',
  platform: '../assets/images/platform.png',
  redCheckmark: '../assets/images/red-checkmark.png',
  renee: '../assets/images/renee.jpg',
  rob: '../assets/images/rob.jpg',
  subscriptionsPreview: '../assets/images/subscriptions-preview.png',
  teamLogo: '../assets/images/8x-team.png',
  tokenHoldersIcon: '../assets/images/token-holders.png',
  travis: '../assets/images/travis.png',
  userIcon: '../assets/images/user.png',
  yellowCheckmark: '../assets/images/yellow-checkmark.png'
};

